# Generated by Django 6.0.2 on 2026-02-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0007_alter_favoritos_unique_together_mascotapersonal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotapersonal',
            name='foto',
        ),
        migrations.AddField(
            model_name='mascotapersonal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
        migrations.AlterField(
            model_name='mascotapersonal',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mascotapersonal',
            name='raza',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
