# Generated by Django 6.0.2 on 2026-02-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0009_mascotapersonal_duenyo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotapersonal',
            name='duenyo',
        ),
    ]
